# -*- coding: utf-8 -*-
"""btvnbuoi6 00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s4WqiDbBxdr8Wp3cIWdXDdxJpGwhBa6h
"""

# Step 1. Import the necessary libraries
import numpy as np 
import pandas as pd

# Step 2. Create a data dictionary that looks like the DataFrame below
record = [('Ivysaur', '45', 'Bulbasaur',  'yes', 'grass'),
          ('Charmeleon', '39', 'Charmander', 'no', 'fire'),
          ('Wartortle', '44', 'Squirtle', 'yes', 'water'),
          ('Metapod', '45', 'Caterpie', 'no', 'bug')]

# Step 3. Assign it to a variable called pokemon
pokemon = pd.DataFrame(data = record, columns=['evolution', 'hp', 'name', 'pokedex', 'type'])

pokemon

# Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place the order of the columns as name, type, hp, evolution, pokedex
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]

pokemon

# Step 5. Add another column called place, and insert what you have in mind.
import random
pokemon_len = len(pokemon)
birthday = [random.randrange(1954, 1990, 1) for i in range(pokemon_len)]
pokemon['birthday'] = birthday
pokemon.tail(4)

pokemon['is_young'] = pokemon['birthday'] > 1980
pokemon.head(4)

# Step 6. Present the type of each column
pokemon.info()
result = pokemon.dtypes
result

# BONUS: Create your own question and answer it.
# take out names that value hp > 40
pokemon[pokemon['hp'] > '40']

